apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: staging
spec:
  encryptedData:
    POSTGRES_USER: AgBSOMEENCRYPTEDPLACEHOLDER1234567890==
    POSTGRES_PASSWORD: AgBOTHERSOMEFAKEENCRYPTEDVALUE0987654321==

