apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: production
spec:
  encryptedData:
    POSTGRES_USER: AgExampleEncryptedUserString
    POSTGRES_PASSWORD: AgExampleEncryptedPasswordString
