apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-deploy-role
rules:
 - apiGroups: [""]
   resources: ["pods","services","configmaps","secrets"]
   verbs: ["get","list","watch","create","update","patch","delete"]
 - apiGroups: ["apps"]
   resources: ["deployments","statefulsets","replicasets"]
   verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deploy-binding
subjects:
 - kind: ServiceAccount
   name: app-deployer
roleRef:
  kind: Role
  name: app-deploy-role
  apiGroup: rbac.authorization.k8s.io
